
package de.thl.intellijinfer.model;

import java.util.ArrayList;
import java.util.List;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Generated by http://www.jsonschema2pojo.org/
 */
public class InferBug {

    @SerializedName("bug_type")
    @Expose
    private String bugType;
    @SerializedName("qualifier")
    @Expose
    private String qualifier;
    @SerializedName("severity")
    @Expose
    private String severity;
    @SerializedName("line")
    @Expose
    private int line;
    @SerializedName("column")
    @Expose
    private int column;
    @SerializedName("procedure")
    @Expose
    private String procedure;
    @SerializedName("procedure_start_line")
    @Expose
    private int procedureStartLine;
    @SerializedName("file")
    @Expose
    private String file;
    @SerializedName("bug_trace")
    @Expose
    private List<BugTrace> bugTrace = new ArrayList<BugTrace>();
    @SerializedName("key")
    @Expose
    private String key;
    @SerializedName("node_key")
    @Expose
    private String nodeKey;
    @SerializedName("hash")
    @Expose
    private String hash;
    @SerializedName("bug_type_hum")
    @Expose
    private String bugTypeHum;
    @SerializedName("censored_reason")
    @Expose
    private String censoredReason;

    /**
     * No args constructor for use in serialization
     * 
     */
    public InferBug() {
    }

    /**
     * 
     * @param censoredReason
     * @param bugTrace
     * @param hash
     * @param bugTypeHum
     * @param line
     * @param qualifier
     * @param severity
     * @param bugType
     * @param file
     * @param column
     * @param procedureStartLine
     * @param procedure
     * @param key
     * @param nodeKey
     */
    public InferBug(String bugType, String qualifier, String severity, int line, int column, String procedure, int procedureStartLine, String file, List<BugTrace> bugTrace, String key, String nodeKey, String hash, String bugTypeHum, String censoredReason) {
        super();
        this.bugType = bugType;
        this.qualifier = qualifier;
        this.severity = severity;
        this.line = line;
        this.column = column;
        this.procedure = procedure;
        this.procedureStartLine = procedureStartLine;
        this.file = file;
        this.bugTrace = bugTrace;
        this.key = key;
        this.nodeKey = nodeKey;
        this.hash = hash;
        this.bugTypeHum = bugTypeHum;
        this.censoredReason = censoredReason;
    }

    public String getBugType() {
        return bugType;
    }

    public void setBugType(String bugType) {
        this.bugType = bugType;
    }

    public String getQualifier() {
        return qualifier;
    }

    public void setQualifier(String qualifier) {
        this.qualifier = qualifier;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public int getLine() {
        return line;
    }

    public void setLine(int line) {
        this.line = line;
    }

    public int getColumn() {
        return column;
    }

    public void setColumn(int column) {
        this.column = column;
    }

    public String getProcedure() {
        return procedure;
    }

    public void setProcedure(String procedure) {
        this.procedure = procedure;
    }

    public int getProcedureStartLine() {
        return procedureStartLine;
    }

    public void setProcedureStartLine(int procedureStartLine) {
        this.procedureStartLine = procedureStartLine;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public List<BugTrace> getBugTrace() {
        return bugTrace;
    }

    public void setBugTrace(List<BugTrace> bugTrace) {
        this.bugTrace = bugTrace;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getNodeKey() {
        return nodeKey;
    }

    public void setNodeKey(String nodeKey) {
        this.nodeKey = nodeKey;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getBugTypeHum() {
        return bugTypeHum;
    }

    public void setBugTypeHum(String bugTypeHum) {
        this.bugTypeHum = bugTypeHum;
    }

    public String getCensoredReason() {
        return censoredReason;
    }

    public void setCensoredReason(String censoredReason) {
        this.censoredReason = censoredReason;
    }

    @Override
    public String toString() {
        return String.format("%s: %s", getBugType(), getQualifier());
    }

    public class BugTrace {

        @SerializedName("level")
        @Expose
        private int level;
        @SerializedName("filename")
        @Expose
        private String filename;
        @SerializedName("line_number")
        @Expose
        private int lineNumber;
        @SerializedName("column_number")
        @Expose
        private int columnNumber;
        @SerializedName("description")
        @Expose
        private String description;

        /**
         * No args constructor for use in serialization
         *
         */
        public BugTrace() {
        }

        public int getLevel() {
            return level;
        }

        public void setLevel(int level) {
            this.level = level;
        }

        public String getFilename() {
            return filename;
        }

        public void setFilename(String filename) {
            this.filename = filename;
        }

        public int getLineNumber() {
            return lineNumber;
        }

        public void setLineNumber(int lineNumber) {
            this.lineNumber = lineNumber;
        }

        public int getColumnNumber() {
            return columnNumber;
        }

        public void setColumnNumber(int columnNumber) {
            this.columnNumber = columnNumber;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        @Override
        public String toString() {
            return String.format("%s Line %d Column %d %s", getFilename(), getLineNumber(), getColumnNumber(), getDescription());
        }
    }
}
